name: Publish documentation website to GitHub Pages
on:
  workflow_dispatch: {}
  push:
    branches: ["*"]

jobs:
  publish:
    name: Publish documentation website

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
        - uses: actions/checkout@v4

        - uses: actions/setup-dotnet@v1
          with:
            dotnet-version: 9.0.x

        - uses: retypeapp/action-build@latest
          with:
            license: ${{ secrets.RETYPE_API_KEY }}

        - uses: alexasselin008/retypeapp-action-build-llms@main
